# Distribution configuration file

# To add a "Featured" section to the site with a set of statically generated
# YARD documentation directories, add your own projects below followed by the
# path to the library root relative to repos/featured. You can also use an
# absolute path.
#
featured:
  puppetlabs-apache: module
  puppetlabs-postgresql: module
  puppet-selinux: module
  puppet-virtualbox: module

#
# You can also add libraries by version:
#
# featured:
#   yard:
#     0.6.4: /path/to/yard/0.6.4
#     0.6.0: /path/to/yard/0.6.0
sponsor: hetzner.com
